# Generated by Django 4.1.5 on 2023-02-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='std_id',
        ),
    ]
