# Generated by Django 4.1.5 on 2023-02-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_name', models.CharField(max_length=200)),
                ('phy', models.PositiveIntegerField()),
                ('chem', models.PositiveIntegerField()),
                ('bio', models.PositiveIntegerField()),
                ('math', models.PositiveIntegerField()),
                ('eng', models.PositiveIntegerField()),
                ('kannada', models.PositiveIntegerField()),
            ],
        ),
    ]
